version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.2.0

jobs:
  fast_track:
    executor: continuation/default
    steps:
      - checkout
      - run:
          name: Fast Track Services
          command: |
            ./.circleci/process.sh
      - continuation/continue:
          configuration_path: .circleci/build_config.template.yml # use newly generated config to continue

workflows:
  init:
    jobs:
      - fast_track
