version: 2.1

commands:
  docker_login:
    description: "Login into Docker Hub service for pulls and pushes"
    steps:
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_TOKEN" | docker login --username viict --password-stdin
  build:
    description: "Run build command from Makefile for a service"
    parameters:
      service_name:
        type: string
    steps:
      - run:
          name: "Build << parameters.service_name >>"
          command: "make -c << parameters.service_name >> build"

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    parameters:
      service_name:
        type: string
    docker:
      - image: cimg/base:stable
    steps:
      - checkout:
          path: ~/project
      - docker_login
      - run:
          name: "Build << parameters.service_name >>"
          command: "make -C << parameters.service_name >> build"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build:
    jobs:
      - build:
          name: "Build API"
          service_name: api

      - build:
          name: "Build Frontend"
          service_name: frontend
